# fly.toml app configuration file generated for poetico on 2025-01-13T22:45:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poetico'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  DEV_MODE = 'false'
  PORT = '8888'

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "poetico_data"
  destination = "/data"
