app = "poetico"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  DEV_MODE = "false"
  PORT = "8888"

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 